import { getExecutableEffects } from "./effectPrograms";
import { resolveEffect } from "./effectResolver";
import type { EffectSelection, PendingTrigger } from "./effectTypes";
import type { BattleEvent, BattleState } from "./types";

/**
 * Drains card lifecycle effects generated by a command or an automatic phase.
 * The triggering event is the snapshot boundary: notably a destroyed card is
 * already in graveyard when its effect runs, so the event retains its former
 * square in scalar data.  Generated events are appended to the same queue,
 * allowing destruction chains while bounding accidental cycles.
 */
export type LifecycleEffectsResolution =
  | { readonly accepted: true; readonly state: BattleState; readonly events: readonly BattleEvent[] }
  | { readonly accepted: false; readonly state: BattleState; readonly events: readonly []; readonly rejection: "trigger-loop" };

const MAX_TRIGGER_DEPTH = 64;

interface QueuedEvent {
  readonly event: BattleEvent;
  readonly depth: number;
}

export function resolveLifecycleEffects(state: BattleState, initialEvents: readonly BattleEvent[]): LifecycleEffectsResolution {
  let next = state;
  const produced: BattleEvent[] = [];
  const queue: QueuedEvent[] = initialEvents.map((event) => ({ event, depth: 0 })).sort(compareQueuedEvent);
  const visited = new Set<string>();
  while (queue.length > 0) {
    const { event, depth } = queue.shift()!;
    const trigger = event.type === "creature.summoned" ? "summon" : event.type === "creature.moved" ? "moved" : event.type === "creature.destroyed" ? "destroyed" : undefined;
    if (!trigger || !event.instanceId) continue;
    const sources = trigger === "destroyed"
      ? destroyedSources(next, event.instanceId)
      : [event.instanceId];
    for (const sourceId of sources.sort()) {
      const source = next.cardInstances[sourceId];
      if (!source) continue;
      for (const effect of getExecutableEffects(source, trigger)) {
        const pending: PendingTrigger = {
          eventSequence: event.sequence,
          sourceInstanceId: sourceId,
          effectId: effect.effectId,
          depth,
          snapshot: { controllerSide: source.controllerSide, targetIds: lifecycleTargetIds(event) }
        };
        const key = `${pending.eventSequence}:${pending.sourceInstanceId}:${pending.effectId}`;
        if (visited.has(key)) continue;
        if (pending.depth > MAX_TRIGGER_DEPTH || visited.size >= MAX_TRIGGER_DEPTH) {
          // The caller must not commit this partially-drained transaction.
          return { accepted: false, state, events: [], rejection: "trigger-loop" };
        }
        visited.add(key);
        const selection = lifecycleSelection(event, trigger);
        const resolved = resolveEffect({ state: next, sourceInstanceId: sourceId, controllerSide: source.controllerSide, effect, selection, firstSequence: next.eventCursor + produced.length + 1 });
        if (!resolved.accepted) continue;
        next = resolved.state;
        produced.push(...resolved.events);
        queue.push(...resolved.events.map((generated) => ({ event: generated, depth: pending.depth + 1 })));
        queue.sort(compareQueuedEvent);
      }
    }
  }
  return { accepted: true, state: produced.length ? { ...next, eventCursor: produced.at(-1)!.sequence } : next, events: produced };
}

function lifecycleTargetIds(event: BattleEvent): readonly string[] {
  return event.instanceId ? [event.instanceId] : [];
}

function compareQueuedEvent(left: QueuedEvent, right: QueuedEvent): number {
  return left.event.sequence - right.event.sequence || left.depth - right.depth || (left.event.instanceId ?? "").localeCompare(right.event.instanceId ?? "");
}

function destroyedSources(state: BattleState, destroyedId: string): string[] {
  const destroyed = state.cardInstances[destroyedId];
  const own = destroyed?.controllerSide;
  return Object.values(state.cardInstances)
    .filter((card) => card.catalogCardId === "AK-056" && card.zone === "board" && card.instanceId !== destroyedId && card.controllerSide === own)
    .map((card) => card.instanceId)
    .concat(destroyed?.catalogCardId === "AK-010" || destroyed?.catalogCardId === "AK-049" || destroyed?.catalogCardId === "AK-051" || destroyed?.catalogCardId === "AK-058" ? [destroyedId] : []);
}

function lifecycleSelection(event: BattleEvent, trigger: "summon" | "moved" | "destroyed"): EffectSelection {
  if (trigger !== "destroyed") return { kind: "none" };
  const column = event.data?.previousColumn;
  const row = event.data?.previousRow;
  return typeof column === "number" && typeof row === "number"
    ? { kind: "structured", value: { coordinates: [{ column, row }] } }
    : { kind: "none" };
}
